site_name: Baza Wiedzy
theme:
  name: material
  language: pl
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Tryb ciemny
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Tryb jasny
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest

plugins:
  - search:
      lang: pl
  - tags:
      tags_file: tags.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
